name: GitHub Pages CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure Git
        run: git config user.name "GitHub Pages CD"

      - name: Install NPM packages
        run: npm install

      - name: Compile Webpack project
        run: npm run build

      - name: Publish build
        run: |
          git add --force dist/
          git commit --message 'Publish site'
          git subtree split --prefix dist/ --branch gh-pages
          git push --force origin gh-pages
