name: PR Linter

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install NPM packages
        run: npm install

      - name: Run linting script
        run: npm run lint
